import { expect, test, type Page } from '@playwright/test'
import { policy } from '../fixtures.js'

async function signIn(page: Page, handle: string) {
  await page.goto('/')
  await page.getByLabel('Handle').fill(handle)
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('heading', { name: 'Your feed policies' })).toBeVisible()
  await expect(page.getByText(`@${handle}`, { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Take a look' })).toBeVisible()
}

test('landing publishes a fetchable large social preview', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('meta[property="og:title"]')).toHaveAttribute('content', 'atproto-acl · Personal feed policy')
  await expect(page.locator('meta[property="og:image"]')).toHaveAttribute('content', 'https://atproto-acl.neutral.zone/social-card.png')
  await expect(page.locator('meta[name="twitter:card"]')).toHaveAttribute('content', 'summary_large_image')
  const image = await page.request.get('/social-card.png')
  expect(image.status()).toBe(200)
  expect(image.headers()['content-type']).toBe('image/png')
  expect((await image.body()).byteLength).toBeGreaterThan(100_000)
  await page.getByRole('banner').getByRole('link', { name: 'Help' }).click()
  await expect(page.getByRole('heading', { name: 'How this works' })).toBeVisible()
  await expect(page.getByText(/a university research group that tracks public posting volume/)).toBeVisible()
})

test('open beta admits a new account as preview-only', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText(/Open limited beta/)).toBeVisible()
  await expect(page.getByLabel(/Invite code/)).toHaveCount(0)
  await signIn(page, 'user5.test')
  await expect(page.getByText('Preview access', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Set up a scan' }).click()
  await page.getByRole('button', { name: 'Save and scan now' }).click()
  await expect(page.getByRole('heading', { name: '2 accounts to review' })).toBeVisible()
  await expect(page.getByText('This is a preview.', { exact: true })).toBeVisible()
  await expect(page.locator('form[action$="/approve"]')).toHaveCount(0)
  await expect(page.getByRole('checkbox', { name: /Select did:/ })).toHaveCount(0)
})

test('skip link appears on focus and moves focus to main content', async ({ page }) => {
  await page.goto('/')
  const skip = page.getByRole('link', { name: 'Skip to content' })
  await expect(skip).not.toBeInViewport()
  await page.keyboard.press('Tab')
  await expect(skip).toBeFocused()
  await expect(skip).toBeInViewport()
  await page.keyboard.press('Enter')
  await expect(page.locator('main')).toBeFocused()
})

test('sign out ends only the current browser session', async ({ browser }) => {
  const first = await browser.newContext()
  const second = await browser.newContext()
  const firstPage = await first.newPage()
  const secondPage = await second.newPage()
  await signIn(firstPage, 'user1.test')
  await signIn(secondPage, 'user1.test')
  await firstPage.getByRole('button', { name: 'Sign out' }).click()
  await expect(firstPage.getByRole('heading', { name: 'Choose what earns your attention.' })).toBeVisible()
  await secondPage.reload()
  await expect(secondPage.getByRole('heading', { name: 'Your feed policies' })).toBeVisible()
  await first.close()
  await second.close()
})

test('a second landing page does not expire an existing sign-in form', async ({ browser }) => {
  const context = await browser.newContext()
  const first = await context.newPage()
  const second = await context.newPage()
  await first.goto('/')
  await second.goto('/')
  await first.getByLabel('Handle').fill('user1.test')
  await first.getByRole('button', { name: 'Continue' }).click()
  await expect(first.getByRole('heading', { name: 'Your feed policies' })).toBeVisible()
  await context.close()
})

test('desktop preview, exact approval, durable execution, and user isolation', async ({ browser }) => {
  const first = await browser.newContext({ viewport: { width: 1280, height: 900 } })
  const page = await first.newPage()
  await signIn(page, 'user1.test')
  await expect(page.getByRole('heading', { name: 'Account-specific rules' })).toBeVisible()
  await page.getByLabel('Add an account').fill('alice.example')
  await page.getByRole('button', { name: 'Add to list' }).click()
  const rule = page.locator('.exception-row').filter({ hasText: '@alice.example' })
  await expect(rule).toContainText('Never touch this account')
  await rule.getByRole('button', { name: 'Remove' }).click()
  await expect(page.locator('.exception-row')).toHaveCount(0)
  const refused = await page.request.post('/overrides', {
    headers: { Origin: 'https://attacker.invalid', 'Content-Type': 'application/x-www-form-urlencoded' },
    data: 'subject=did%3Aplc%3Aalice&kind=exempt&enabled=1',
  })
  expect(refused.status()).toBe(403)
  await page.getByRole('link', { name: 'Set up a scan' }).click()
  await page.getByLabel('Policy name').fill('Attention test')
  await expect(page.getByLabel('Which accounts to check')).toHaveValue('feeds')
  await expect(page.getByText('Checks up to 500 accounts from your Following and Discover feeds')).toBeVisible()
  await expect(page.getByLabel('Policy YAML')).not.toBeVisible()
  await page.getByRole('button', { name: 'Save for later' }).click()
  const policyUrl = page.url()
  await page.getByRole('button', { name: 'Scan my feed' }).click()
  const previewUrl = page.url()
  await expect(page.getByRole('heading', { name: '2 accounts to review' })).toBeVisible()
  await expect(page.getByText('1 to mute. 1 you follow, listed separately.')).toBeVisible()
  await expect(page.getByText(/Looked at 3 accounts from your Following and Discover feeds/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'To mute 1' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'People you follow 1' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Leaving alone 1' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Couldn’t tell/ })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Alice' })).toBeVisible()
  await expect(page.getByText('@alice.example')).toBeVisible()
  const followed = page.locator('.followed-review')
  await expect(followed).not.toBeVisible()
  await page.getByRole('button', { name: 'People you follow 1' }).click()
  await expect(followed).toBeVisible()
  await expect(followed).not.toHaveAttribute('open', '')
  await expect(followed.getByText('These are people you chose to follow')).not.toBeVisible()
  await followed.getByText('Accounts you follow').click()
  await expect(followed.getByText('These are people you chose to follow')).toBeVisible()
  await expect(followed.getByLabel('Select did:plc:bob')).not.toBeChecked()
  await expect(followed.getByRole('button', { name: /Mute/ })).toHaveAttribute('value', 'apply_followed')
  await page.getByRole('button', { name: 'Leaving alone 1' }).click()
  await expect(page.getByText('Nothing on record', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'To mute 1' }).click()
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/desktop-preview.png', fullPage: true })
  }
  await page.getByLabel('Select did:plc:alice').check()
  await page.getByRole('button', { name: /^Mute 1 account$/ }).click()
  await expect(page.getByRole('heading', { name: /Muting 1 account|1 account muted/ })).toBeVisible()
  const jobUrl = page.url()
  await expect.poll(async () => {
    await page.reload()
    return (await page.locator('.title .status').textContent())?.trim()
  }).toBe('completed')
  await expect(page.getByText('Muted', { exact: true })).toBeVisible()
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/action-results.png', fullPage: true })
  }
  await expect(page.getByRole('progressbar')).toHaveAttribute('value', '1')
  await expect(page.getByText('Mute (private)')).toBeVisible()
  await expect(page.getByRole('link', { name: 'View profile' })).toHaveAttribute('href', 'https://bsky.app/profile/did:plc:alice')
  await page.getByText('Seen 2 times · view sampled posts').click()
  await expect(page.getByRole('link', { name: /View sampled post/ }).first()).toHaveAttribute('target', '_blank')
  await expect(page.getByText('did:plc:alice')).not.toBeVisible()
  await page.getByText('Technical details', { exact: true }).click()
  await expect(page.getByText('did:plc:alice')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Muted', { exact: true })).toBeVisible()
  await page.goto('/app')
  await expect(page.getByRole('heading', { name: 'Your feed policies' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Scan my feed' }).first()).toBeVisible()
  await expect(page.getByText(/Last scan found/).first()).toBeVisible()
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/dashboard.png', fullPage: true })
  }

  const second = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const mobile = await second.newPage()
  await signIn(mobile, 'user2.test')
  for (const privateUrl of [policyUrl, previewUrl, jobUrl]) {
    const response = await mobile.goto(privateUrl)
    expect(response?.status()).toBe(404)
    await expect(mobile.getByRole('heading', { name: 'Page not found' })).toBeVisible()
    await expect(mobile.locator('body')).not.toContainText('did:plc:alice')
  }
  await second.close()
  await first.close()
})

test('mobile layout has labeled keyboard-operable policy controls and disconnect', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page, 'user2.test')
  await page.keyboard.press('Tab')
  await page.getByRole('link', { name: 'Set up a scan' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('Policy name')).toHaveValue('Poasters Quarantine')
  await expect(page.getByLabel('Which accounts to check')).toBeVisible()
  await expect(page.getByLabel('Policy YAML')).not.toBeVisible()
  await page.getByText('Advanced · View or edit the YAML').click()
  await expect(page.getByLabel('Policy YAML')).toBeVisible()
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/mobile-policy.png', fullPage: true })
  }
  await page.goto('/app')
  await page.getByText('Connection and account data').click()
  await page.getByRole('button', { name: 'Disconnect this app' }).click()
  await expect(page.getByRole('heading', { name: 'App disconnected' })).toBeVisible()
  await expect(page.getByText(/Anyone you muted stays muted/)).toBeVisible()
})

test('privacy and account deletion are distinct from disconnect', async ({ page }) => {
  await signIn(page, 'user3.test')
  await page.goto('/privacy')
  await expect(page.getByRole('heading', { name: 'What atproto-acl reads and keeps' })).toBeVisible()
  await expect(page.getByText('Ordinary backup copies expire within 30 days.')).toBeVisible()
  await page.getByRole('link', { name: 'Delete my atproto-acl data' }).click()
  await expect(page.getByRole('heading', { name: 'Delete my atproto-acl data' })).toBeVisible()
  await expect(page.getByText('Delete my data, leave my mutes alone')).toBeVisible()
  await page.getByLabel('I understand that accounts I muted will stay muted.').check()
  await page.getByRole('button', { name: 'Delete my data, keep mutes' }).click()
  await expect(page.getByRole('heading', { name: 'Your data has been deleted' })).toBeVisible()
  await page.goto('/app')
  await expect(page).toHaveURL('/')
})

test('read-only feed yield report explains both surfaces and exact context', async ({ page }) => {
  await signIn(page, 'user4.test')
  await page.getByRole('button', { name: 'Take a look' }).click()
  await expect(page.getByRole('heading', { name: '2 accounts would match' })).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText('1 could be muted · 1 you follow, listed separately.')).toBeVisible()
  await expect(page.getByText(/This was a look, not a change/)).toBeVisible()
  await expect(page.getByText(/Following: 137 posts · 137 accounts · 137 not seen in another feed/)).toBeVisible()
  await expect(page.getByText(/Discover: 137 posts · 137 accounts · 0 not seen in another feed/)).toBeVisible()
  await expect(page.getByRole('link', { name: 'View profile' }).first()).toHaveAttribute('href', 'https://bsky.app/profile/did:plc:alice')
  await page.getByText('Seen 2 times · view sampled posts').first().click()
  await expect(page.getByRole('link', { name: /View sampled post/ }).first()).toHaveAttribute('target', '_blank')
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/feed-measurement.png', fullPage: true })
  }
})

test('long-running read-only submit immediately warns against refresh', async ({ page }) => {
  await signIn(page, 'user4.test')
  await expect(page.getByRole('heading', { name: 'Sign in again to include Discover' })).toBeVisible()
  await expect(page.locator('form[action="/reconnect"]')).toContainText('Sign in again')
  await page.locator('form[action="/diagnostics/yield"]').evaluate(form => {
    form.addEventListener('submit', event => event.preventDefault(), { once: true })
  })
  await page.getByRole('button', { name: 'Take a look' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Reading your feeds' })).toBeVisible()
  await expect(page.getByText(/It keeps going if you go back to the dashboard/)).toBeVisible()
  await expect(page.locator('body')).toHaveAttribute('aria-busy', 'true')
  await page.reload()
  await page.getByRole('button', { name: 'Sign in again' }).click()
  await expect(page.getByRole('heading', { name: 'Your feed policies' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Sign in again to include Discover' })).toHaveCount(0)
})

test('empty account preview is truthful and has no approval controls', async ({ page }) => {
  await signIn(page, 'user3.test')
  await page.getByRole('link', { name: 'Set up a scan' }).click()
  await page.getByRole('button', { name: 'Save for later' }).click()
  await page.getByRole('button', { name: 'Scan my feed' }).click()
  await expect(page.getByRole('heading', { name: 'Nothing to change' })).toBeVisible()
  await expect(page.getByText('None of these accounts match your rules right now.')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Nothing for you to approve' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Approve selected/ })).toHaveCount(0)
})

test('invalid advanced YAML stays editable with line diagnostics', async ({ page }) => {
  await signIn(page, 'user1.test')
  await page.goto('/policies/new')
  await page.getByText('Advanced · View or edit the YAML').click()
  await page.getByLabel('Policy YAML').fill('version: 1\nversion: 2')
  await page.getByRole('button', { name: 'Check and save YAML' }).click()
  await expect(page.getByRole('alert')).toContainText("duplicate YAML key 'version' at line 2, column 1")
  await expect(page.getByLabel('Policy YAML')).toHaveValue('version: 1\nversion: 2')
})

test('advanced policy keeps unavailable evidence distinct from a no-match', async ({ page }) => {
  await signIn(page, 'user1.test')
  await page.goto('/policies/new')
  await page.getByText('Advanced · View or edit the YAML').click()
  await page.getByLabel('Policy YAML').fill(policy('did:plc:user1'))
  await page.getByRole('button', { name: 'Check and save YAML' }).click()
  await expect(page.getByText('Hand-written policy', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Which accounts to check')).toHaveCount(0)
  await page.getByRole('button', { name: 'Scan my feed' }).click()
  await expect(page.getByText(/Some posting data couldn’t be fetched./)).toBeVisible()
  await expect(page.getByText(/Some accounts couldn’t be decided one way or the other./)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Couldn’t tell 1' })).toBeVisible()
  await page.getByRole('button', { name: 'Couldn’t tell 1' }).click()
  await expect(page.getByText('Not enough information')).toBeVisible()
  await expect(page.getByText('Posts less than your rules allow', { exact: true })).toHaveCount(0)
})

test('populated preview reconciles totals and searches by handle on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page, 'user4.test')
  await page.getByRole('link', { name: 'Set up a scan' }).click()
  await page.getByRole('button', { name: 'Save for later' }).click()
  await page.getByRole('button', { name: 'Scan my feed' }).click()
  await expect(page.getByRole('heading', { name: '2 accounts to review' })).toBeVisible()
  await expect(page.getByText('1 to mute. 1 you follow, listed separately.')).toBeVisible()
  await expect(page.getByRole('link', { name: 'View profile' }).first()).toHaveAttribute('href', 'https://bsky.app/profile/did:plc:alice')
  await page.getByText('Seen 2 times · view sampled posts').first().click()
  await expect(page.getByRole('link', { name: /View sampled post/ }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Tick all 1' }).first().click()
  await expect(page.getByLabel('Select did:plc:alice')).toBeChecked()
  await page.getByRole('button', { name: 'Clear' }).first().click()
  await expect(page.getByLabel('Select did:plc:alice')).not.toBeChecked()
  await page.getByRole('button', { name: 'Leaving alone 135' }).click()
  await expect(page.locator('[data-result-group="unchanged"] .result:visible')).toHaveCount(20)
  await expect(page.getByText('Page 1 of 7')).toBeVisible()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByText('Page 2 of 7')).toBeVisible()
  await page.getByLabel('Search these results').fill('account-100.example')
  await page.getByRole('button', { name: 'Search' }).click()
  await expect(page.locator('.result')).toHaveCount(1)
  await expect(page.getByText('@account-100.example')).toBeVisible()
  const overflow = await page.evaluate(() => [...document.querySelectorAll<HTMLElement>('body *')]
    .filter(element => element.getBoundingClientRect().right > window.innerWidth + 1)
    .map(element => ({ tag: element.tagName, className: element.className, right: Math.round(element.getBoundingClientRect().right) })))
  expect(overflow).toEqual([])
})

test('Bsky38 preset retains ranked snapshot evidence and offers an exact opt-out batch', async ({ page }) => {
  await signIn(page, 'user4.test')
  await page.goto('/policies/new?example=bsky38')
  await expect(page.locator('input[name="source_type"]')).toHaveValue('external_snapshot')
  await expect(page.getByText(/A separate policy that uses the 38 accounts on the leaderboard/)).toBeVisible()
  await expect(page.getByText('Being on the Bsky38 leaderboard.')).toBeVisible()
  await page.getByRole('button', { name: 'Save and scan now' }).click()
  await expect(page.getByRole('heading', { name: '38 accounts to review' })).toBeVisible()
  await expect(page.getByText('38 to mute.')).toBeVisible()
  await expect(page.getByText(/Bsky38 rank #1 · 1,000 votes · snapshot/)).toBeVisible()
  await expect(page.locator('.result')).toHaveCount(38)
  await expect(page.locator('.result').first()).toContainText('On the Bsky38 leaderboard when you scanned.')
  await expect(page.getByLabel('Select did:plc:bsky38-1', { exact: true })).not.toBeChecked()
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/bsky38-preview.png', fullPage: true })
  }
})
