import { expect, test, type Page } from '@playwright/test'
import { policy } from '../fixtures.js'

async function signIn(page: Page, handle: string) {
  await page.goto('/')
  await page.getByLabel('Handle').fill(handle)
  await page.getByRole('button', { name: 'Continue securely' }).click()
  await expect(page.getByRole('heading', { name: 'Your feed policies' })).toBeVisible()
  await expect(page.getByText(`@${handle}`, { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Measure feed coverage' })).toBeVisible()
}

test('landing publishes a fetchable large social preview', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('meta[property="og:title"]')).toHaveAttribute('content', 'atproto-acl · Personal feed policy')
  await expect(page.locator('meta[property="og:image"]')).toHaveAttribute('content', 'https://atproto-acl.neutral.zone/social-card.png')
  await expect(page.locator('meta[name="twitter:card"]')).toHaveAttribute('content', 'summary_large_image')
  const image = await page.request.get('/social-card.png')
  expect(image.status()).toBe(200)
  expect(image.headers()['content-type']).toBe('image/png')
  expect((await image.body()).byteLength).toBeGreaterThan(100_000)
  await page.getByRole('link', { name: 'Help' }).click()
  await expect(page.getByRole('heading', { name: 'How previews and changes work' })).toBeVisible()
  await expect(page.getByText('A maximum limits that source; it does not invent more accounts.')).toBeVisible()
})

test('skip link appears on focus and moves focus to main content', async ({ page }) => {
  await page.goto('/')
  const skip = page.getByRole('link', { name: 'Skip to content' })
  await expect(skip).not.toBeInViewport()
  await page.keyboard.press('Tab')
  await expect(skip).toBeFocused()
  await expect(skip).toBeInViewport()
  await page.keyboard.press('Enter')
  await expect(page.locator('main')).toBeFocused()
})

test('a second landing page does not expire an existing sign-in form', async ({ browser }) => {
  const context = await browser.newContext()
  const first = await context.newPage()
  const second = await context.newPage()
  await first.goto('/')
  await second.goto('/')
  await first.getByLabel('Handle').fill('user1.test')
  await first.getByRole('button', { name: 'Continue securely' }).click()
  await expect(first.getByRole('heading', { name: 'Your feed policies' })).toBeVisible()
  await context.close()
})

test('desktop preview, exact approval, durable execution, and user isolation', async ({ browser }) => {
  const first = await browser.newContext({ viewport: { width: 1280, height: 900 } })
  const page = await first.newPage()
  await signIn(page, 'user1.test')
  const refused = await page.request.post('/overrides', {
    headers: { Origin: 'https://attacker.invalid', 'Content-Type': 'application/x-www-form-urlencoded' },
    data: 'subject=did%3Aplc%3Aalice&kind=exempt&enabled=1',
  })
  expect(refused.status()).toBe(403)
  await page.getByRole('link', { name: 'Configure Poasters Quarantine' }).click()
  await page.getByLabel('Policy name').fill('Attention test')
  await expect(page.getByLabel('Account source')).toHaveValue('feeds')
  await expect(page.getByText('Check up to 500 accounts appearing in your Timeline and Discover feeds')).toBeVisible()
  await expect(page.getByLabel('Policy YAML')).not.toBeVisible()
  await page.getByRole('button', { name: 'Save policy' }).click()
  const policyUrl = page.url()
  await page.getByRole('button', { name: 'Build preview' }).click()
  const previewUrl = page.url()
  await expect(page.getByRole('heading', { name: 'Checked 3 accounts from @user1.test’s Timeline and Discover feeds' })).toBeVisible()
  await expect(page.getByText('1 new mute proposed. 1 followed account needs separate review.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Proposed changes 1' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Followed review 1' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'No change 1' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Unresolved 0' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Alice' })).toBeVisible()
  await expect(page.getByText('@alice.example')).toBeVisible()
  const followed = page.locator('.followed-review')
  await expect(followed).not.toBeVisible()
  await page.getByRole('button', { name: 'Followed review 1' }).click()
  await expect(followed).toBeVisible()
  await expect(followed).not.toHaveAttribute('open', '')
  await expect(followed.getByText('Review these separately')).not.toBeVisible()
  await followed.getByText('Followed accounts that matched').click()
  await expect(followed.getByText('Review these separately')).toBeVisible()
  await expect(followed.getByLabel('Select did:plc:bob')).not.toBeChecked()
  await expect(followed.getByRole('button', { name: 'Approve selected followed-account mutes' })).toHaveAttribute('value', 'apply_followed')
  await page.getByRole('button', { name: 'No change 1' }).click()
  await expect(page.getByText('No matching evidence found', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Proposed changes 1' }).click()
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/desktop-preview.png', fullPage: true })
  }
  await page.getByLabel('Select did:plc:alice').check()
  await page.getByRole('button', { name: 'Approve selected mutes' }).click()
  await expect(page.getByRole('heading', { name: /Applying 1 change|1 account muted/ })).toBeVisible()
  const jobUrl = page.url()
  await expect.poll(async () => {
    await page.reload()
    return (await page.locator('.title .status').textContent())?.trim()
  }).toBe('completed')
  await expect(page.getByText('Muted', { exact: true })).toBeVisible()
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/action-results.png', fullPage: true })
  }
  await expect(page.getByRole('progressbar')).toHaveAttribute('value', '1')
  await expect(page.getByText('Add private mute')).toBeVisible()
  await expect(page.getByRole('link', { name: 'View profile' })).toHaveAttribute('href', 'https://bsky.app/profile/did:plc:alice')
  await page.getByText('Seen 2 times · view sampled posts').click()
  await expect(page.getByRole('link', { name: /View sampled post/ }).first()).toHaveAttribute('target', '_blank')
  await expect(page.getByText('did:plc:alice')).not.toBeVisible()
  await page.getByText('Technical details', { exact: true }).click()
  await expect(page.getByText('did:plc:alice')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Muted', { exact: true })).toBeVisible()
  await page.goto('/app')
  await expect(page.getByRole('heading', { name: 'Your feed policies' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Preview accounts' }).first()).toBeVisible()
  await expect(page.getByText(/Last preview proposed|proposed change/).first()).toBeVisible()
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/dashboard.png', fullPage: true })
  }

  const second = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const mobile = await second.newPage()
  await signIn(mobile, 'user2.test')
  for (const privateUrl of [policyUrl, previewUrl, jobUrl]) {
    const response = await mobile.goto(privateUrl)
    expect(response?.status()).toBe(404)
    await expect(mobile.getByRole('heading', { name: 'Page not found' })).toBeVisible()
    await expect(mobile.locator('body')).not.toContainText('did:plc:alice')
  }
  await second.close()
  await first.close()
})

test('mobile layout has labeled keyboard-operable policy controls and disconnect', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page, 'user2.test')
  await page.keyboard.press('Tab')
  await page.getByRole('link', { name: 'Configure Poasters Quarantine' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('Policy name')).toHaveValue('Poasters Quarantine')
  await expect(page.getByLabel('Account source')).toBeVisible()
  await expect(page.getByLabel('Policy YAML')).not.toBeVisible()
  await page.getByText('Advanced · View or edit policy YAML').click()
  await expect(page.getByLabel('Policy YAML')).toBeVisible()
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/mobile-policy.png', fullPage: true })
  }
  await page.goto('/app')
  await page.getByRole('button', { name: 'Disconnect', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Account disconnected' })).toBeVisible()
  await expect(page.getByText('Existing mutes remain')).toBeVisible()
})

test('privacy and account deletion are distinct from disconnect', async ({ page }) => {
  await signIn(page, 'user3.test')
  await page.goto('/privacy')
  await expect(page.getByRole('heading', { name: 'What atproto-acl reads and keeps' })).toBeVisible()
  await expect(page.getByText('Ordinary backup copies expire within 30 days.')).toBeVisible()
  await page.getByRole('link', { name: 'Delete my atproto-acl data' }).click()
  await expect(page.getByRole('heading', { name: 'Delete my atproto-acl data' })).toBeVisible()
  await expect(page.getByText('Delete data; leave existing Bluesky mutes unchanged')).toBeVisible()
  await page.getByLabel('I understand that existing Bluesky mutes will remain.').check()
  await page.getByRole('button', { name: 'Delete data and leave mutes' }).click()
  await expect(page.getByRole('heading', { name: 'Your atproto-acl data was deleted' })).toBeVisible()
  await page.goto('/app')
  await expect(page).toHaveURL('/')
})

test('read-only feed yield report explains both surfaces and exact context', async ({ page }) => {
  await signIn(page, 'user4.test')
  await page.getByRole('button', { name: 'Measure feed coverage' }).click()
  await expect(page.getByRole('heading', { name: '2 accounts matched' })).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText('1 proposed mute · 1 person you follow for separate review.')).toBeVisible()
  await expect(page.getByText('This measurement made no moderation changes.')).toBeVisible()
  await expect(page.getByText(/Timeline: 137 items · 137 authors · 137 new beyond earlier sources/)).toBeVisible()
  await expect(page.getByText(/Discover: 137 items · 137 authors · 0 new beyond earlier sources/)).toBeVisible()
  await expect(page.getByRole('link', { name: 'View profile' }).first()).toHaveAttribute('href', 'https://bsky.app/profile/did:plc:alice')
  await page.getByText('Seen 2 times · view sampled posts').first().click()
  await expect(page.getByRole('link', { name: /View sampled post/ }).first()).toHaveAttribute('target', '_blank')
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/feed-measurement.png', fullPage: true })
  }
})

test('long-running read-only submit immediately warns against refresh', async ({ page }) => {
  await signIn(page, 'user4.test')
  await expect(page.getByRole('heading', { name: 'Reconnect before checking Discover' })).toBeVisible()
  await expect(page.locator('form[action="/reconnect"]')).toContainText('Reconnect with Discover access')
  await page.locator('form[action="/diagnostics/yield"]').evaluate(form => {
    form.addEventListener('submit', event => event.preventDefault(), { once: true })
  })
  await page.getByRole('button', { name: 'Measure feed coverage' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Starting a fresh measurement' })).toBeVisible()
  await expect(page.getByText('You can return to the dashboard while the read-only check continues.')).toBeVisible()
  await expect(page.locator('body')).toHaveAttribute('aria-busy', 'true')
  await page.reload()
  await page.getByRole('button', { name: 'Reconnect with Discover access' }).click()
  await expect(page.getByRole('heading', { name: 'Your feed policies' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Reconnect before checking Discover' })).toHaveCount(0)
})

test('empty account preview is truthful and has no approval controls', async ({ page }) => {
  await signIn(page, 'user3.test')
  await page.getByRole('link', { name: 'Configure Poasters Quarantine' }).click()
  await page.getByRole('button', { name: 'Save policy' }).click()
  await page.getByRole('button', { name: 'Build preview' }).click()
  await expect(page.getByRole('heading', { name: 'Checked 0 accounts from @user3.test’s Timeline and Discover feeds' })).toBeVisible()
  await expect(page.getByText('No changes proposed.')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'No changes to approve' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Approve selected/ })).toHaveCount(0)
})

test('invalid advanced YAML stays editable with line diagnostics', async ({ page }) => {
  await signIn(page, 'user1.test')
  await page.goto('/policies/new')
  await page.getByText('Advanced · View or edit policy YAML').click()
  await page.getByLabel('Policy YAML').fill('version: 1\nversion: 2')
  await page.getByRole('button', { name: 'Validate and save YAML' }).click()
  await expect(page.getByRole('alert')).toContainText("duplicate YAML key 'version' at line 2, column 1")
  await expect(page.getByLabel('Policy YAML')).toHaveValue('version: 1\nversion: 2')
})

test('advanced policy keeps unavailable evidence distinct from a no-match', async ({ page }) => {
  await signIn(page, 'user1.test')
  await page.goto('/policies/new')
  await page.getByText('Advanced · View or edit policy YAML').click()
  await page.getByLabel('Policy YAML').fill(policy('did:plc:user1'))
  await page.getByRole('button', { name: 'Validate and save YAML' }).click()
  await expect(page.getByText('Advanced policy', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Account source')).toHaveCount(0)
  await page.getByRole('button', { name: 'Build preview' }).click()
  await expect(page.getByText('Some evidence-source checks were unavailable.')).toBeVisible()
  await expect(page.getByText('Some policy results could not be decided safely.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Unresolved 1' })).toBeVisible()
  await page.getByRole('button', { name: 'Unresolved 1' }).click()
  await expect(page.getByText('Couldn’t decide safely')).toBeVisible()
  await expect(page.getByText('No matching label found', { exact: true })).toHaveCount(0)
})

test('populated preview reconciles totals and searches by handle on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page, 'user4.test')
  await page.getByRole('link', { name: 'Configure Poasters Quarantine' }).click()
  await page.getByRole('button', { name: 'Save policy' }).click()
  await page.getByRole('button', { name: 'Build preview' }).click()
  await expect(page.getByRole('heading', { name: 'Checked 137 accounts from @user4.test’s Timeline and Discover feeds' })).toBeVisible()
  await expect(page.getByText('1 new mute proposed. 1 followed account needs separate review.')).toBeVisible()
  await expect(page.getByRole('link', { name: 'View profile' }).first()).toHaveAttribute('href', 'https://bsky.app/profile/did:plc:alice')
  await page.getByText('Seen 2 times · view sampled posts').first().click()
  await expect(page.getByRole('link', { name: /View sampled post/ }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Select all proposed changes' }).click()
  await expect(page.getByLabel('Select did:plc:alice')).toBeChecked()
  await page.getByRole('button', { name: 'Select none' }).first().click()
  await expect(page.getByLabel('Select did:plc:alice')).not.toBeChecked()
  await page.getByRole('button', { name: 'No change 135' }).click()
  await expect(page.locator('[data-result-group="unchanged"] .result:visible')).toHaveCount(20)
  await expect(page.getByText('Page 1 of 7')).toBeVisible()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByText('Page 2 of 7')).toBeVisible()
  await page.getByLabel('Search results').fill('account-100.example')
  await page.getByRole('button', { name: 'Search' }).click()
  await expect(page.locator('.result')).toHaveCount(1)
  await expect(page.getByText('@account-100.example')).toBeVisible()
  const overflow = await page.evaluate(() => [...document.querySelectorAll<HTMLElement>('body *')]
    .filter(element => element.getBoundingClientRect().right > window.innerWidth + 1)
    .map(element => ({ tag: element.tagName, className: element.className, right: Math.round(element.getBoundingClientRect().right) })))
  expect(overflow).toEqual([])
})

test('Bsky38 preset retains ranked snapshot evidence and offers an exact opt-out batch', async ({ page }) => {
  await signIn(page, 'user4.test')
  await page.goto('/policies/new?example=bsky38')
  await expect(page.locator('input[name="source_type"]')).toHaveValue('external_snapshot')
  await expect(page.getByText('This separate policy uses a pinned 38-account snapshot.')).toBeVisible()
  await expect(page.getByText('Included in the Bsky38 leaderboard snapshot.')).toBeVisible()
  await page.getByRole('button', { name: 'Save and preview' }).click()
  await expect(page.getByRole('heading', { name: 'Checked the current 38-account Bsky38 snapshot' })).toBeVisible()
  await expect(page.getByText('38 new mutes proposed.')).toBeVisible()
  await expect(page.getByText(/Bsky38 rank #1 · 1,000 votes · snapshot/)).toBeVisible()
  await expect(page.locator('.result')).toHaveCount(38)
  await expect(page.locator('.result').first()).toContainText('Included in the Bsky38 leaderboard snapshot.')
  await expect(page.getByLabel('Select did:plc:bsky38-1', { exact: true })).not.toBeChecked()
  if (process.env.ATPROTO_ACL_SCREENSHOT_DIR) {
    await page.screenshot({ path: process.env.ATPROTO_ACL_SCREENSHOT_DIR + '/bsky38-preview.png', fullPage: true })
  }
})
